app/posts/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class create_post(Form):
    title = StringField('Title',validators= [ DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

app/main/routes.py
from flask import render_template, request, Blueprint,redirect,url_for,flash
from app import db
from app.models import Post,Announcments
from flask_login import current_user,login_required
from app.main.forms import Announcment

main = Blueprint('main',__name__)

@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page',1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)   
    return render_template("home.html", post = posts , title = "Home", announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))

@main.route('/about')
def about():
    return render_template("about.html", announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))

@main.route('/announcment',methods=['POST','GET'])
@login_required
def announcment():
    if current_user.username == "Sourad80":
        form = Announcment()
        if form.validate_on_submit():
            announcment = Announcments(title = form.title.data)
            db.session.add(announcment)
            db.session.commit()
            flash(f'Announced', 'success')
            return redirect(url_for('main.home'))
        return render_template("announcment.html",title = "Announce", form = form, announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))
    flash(f'You are not a site admin!', 'danger')
    return redirect(url_for('main.home'))

app/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from app import db
from app.models import Post,Announcments
from app.posts.forms import create_post

posts = Blueprint('posts',__name__)

@posts.route('/post_new',methods=['POST','GET'])
@login_required
def post_new():
    form = create_post()
    if form.validate_on_submit():
        post = Post(title = form.title.data, content = form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash(f'Post created','success')
        return redirect(url_for('main.home'))
    return render_template("create_post.html",title = "Create Post", legend = "Create Post" ,form = form, announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html",title = post.title, post = post, announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))

@posts.route('/post/<int:post_id>/update',methods=['POST','GET'])
@login_required
def post_update(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(404)
    form = create_post()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash(f'Post Updated','success')
        return redirect(url_for('posts.post', post_id = post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content 
    return render_template("create_post.html",title = "Update Post",legend = "Update Post", form = form, announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))

@posts.route('/post/<int:post_id>/delete',methods=['POST'])
@login_required
def post_delete(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(404)
    db.session.delete(post)
    db.session.commit()
    flash(f'Post Deleted','warning')
    return redirect(url_for('main.home'))

app/users/routes.py
from flask import render_template,url_for,redirect,flash,request,Blueprint
from app.users.forms import Registration, Login, Update, request_reset_password,reset_password
from app import db,bcrypt
from app.models import User,Post,Announcments
from PIL import Image
from flask_login import login_user,current_user,logout_user,login_required
from app.users.utils import save_image, send_reset_email

users = Blueprint('users',__name__)

@users.route('/register',methods=['POST','GET'])
def register():
    if current_user.is_authenticated:
        flash(f'Logged in as {user.username}!', 'success')
        return redirect(url_for('main.home'))

    form = Registration()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('Utf-8')
        user = User(username = form.username.data, email = form.email.data, password = hashed_password )
        db.session.add(user)
        db.session.commit()
        flash(f'Created New Account.You can Login now', 'success')
        return redirect(url_for('main.home'))
    return render_template("register.html", title = "Sign Up", form = form, announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))

@users.route('/login',methods=['POST','GET'])
def login():
    if current_user.is_authenticated:
        flash(f'Already loged in', 'success')
        return redirect(url_for('main.home'))
    
    form = Login()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember= form.remember.data)
            next_page = request.args.get('next')
            flash(f'Logged in as {user.username}!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Failed login!!!!! Check email and password!!', 'danger')
    return render_template("login.html", title = "Login", form = form, announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account',methods=['POST','GET'])
@login_required
def account():
    form = Update()
    if form.validate_on_submit():
        if form.image.data:
            image_filename = save_image(form.image.data)
            temp = current_user.image_file
            current_user.image_file = image_filename
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash(f'Account Upated','success')
        redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image = url_for('static', filename = 'profile_pics/' + current_user.image_file)
    return render_template("account.html", title = "Account",form = form,image = image, announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))

@users.route('/user/<string:username>')
def user_post(username):
    page = request.args.get('page',1, type=int)
    user = User.query.filter_by(username = username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=1) 
    title = username + ' Activity'
    image = url_for('static', filename = 'profile_pics/' + user.image_file)
    return render_template("user_posts.html", post = posts ,image = image, user = user, title = title, announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10) )

@users.route('/request_password',methods=['POST','GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = request_reset_password()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash(f'An reset password link have been sent to the registered mail','info')
        return redirect(url_for('users.login'))

    return render_template('reset_request.html',title="Reset Password",form=form, announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))

@users.route('/reset_password/<token>',methods=['POST','GET'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash(f'The token is invalid or expired','warning')
        return redirect(url_for('users.reset_request'))
    form = reset_password()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html',title="Reset Password",form=form, announcements = Announcments.query.order_by(Announcments.date_posted.desc()).paginate(page=1, per_page=10))

app/templates/about.html
{% extends "layout.html" %}
{% block content %}     
    <h1>This blog site is made by Sourad80</h1>
{% endblock content %}

app/templates/account.html
{% extends "layout.html" %}
{% block content %}     
<div class="content-section ">
    <div class="media">
      <img class="rounded-circle account-img" src=" {{ image }} ">
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Form</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                            {% for error in form.username.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.image.label() }}
                    {{ form.image(class="form-control-file") }}
                    {% if form.image.errors %}
                        {% for error in form.image.errors %}
                            <span>{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
  </div>
{% endblock content %}

app/templates/announcment.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Announce</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
                <div class = "form-group">
                    {{ form.submit(class = "btn btn-outline-info") }}
                </div>
        </form>
    </div>
{% endblock content %}

app/templates/create_post.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class = "form-group">
                    {{ form.title.label(class = "form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class = "form-group">
                    {{ form.content.label(class = "form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
                <div class = "form-group">
                    {{ form.submit(class = "btn btn-outline-info") }}
                </div>
        </form>
    </div>
{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}

{% block content %}
    {% for post in post.items %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src=" {{ url_for('static', filename='profile_pics/' + post.author.image_file)}}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_post', username = post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime("%d/%m/%Y  %I:%M %p") }}</small>
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
    {% for page_num in post.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
      {% if page_num %}
        {% if post.page == page_num %}
          <span class="btn btn-outline-info mb-4 active">{{ page_num }}</span>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>{{title}}</title>
    {% else %}
        <title>Blog Site</title>
    {% endif %}
</head>
<body>
  <header class = "site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Blog by Sourad80</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('posts.post_new') }}">Create New Post</a>
              {% if current_user.username == 'Sourad80' %}
                <a class="nav-item nav-link" href="{{ url_for('main.announcment') }}">New Announcement</a>
              {% endif %}
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}">{{ current_user.username }}</a>
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Log out</a>
            {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    </header>


      <main role="main" class="container" style="padding-top: 70px;">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Announcements</h3>
              <p class='text-muted'>Keeps yourself updated about our site
                <ul class="list-group">
                  {% for announcment in announcements.items %}
                    <li class="list-group-item list-group-item-light">{{ announcment.title }}</li>
                  {% endfor %}
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>


      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
  </html>
  

app/templates/login.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class = "form-group">
                    {{ form.email.label(class = "form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class = "form-group">
                    {{ form.password.label(class = "form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
                <div class = "form-group">
                    {{ form.submit(class = "btn btn-outline-info") }}
                </div>
            <small class="text-muted ml-2">
                <a href="{{url_for('users.reset_request')}}">Forgot password</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            New User??<br><a href="{{ url_for('users.register') }}">Create New Accout</a>
        </small>
    </div>
{% endblock content %}

app/templates/post.html
{% extends "layout.html" %}

{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src=" {{ url_for('static', filename='profile_pics/' + post.author.image_file)}}">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime("%d/%m/%Y  %I:%M %p") }}</small>
            {% if post.author == current_user %}
                <a class="btn btn-secondary btn-sm mb-1 float-right" href="{{url_for('posts.post_update', post_id = post.id)}}">Update</a>
                <button type="button" class="btn btn-danger btn-sm mr-1 float-right" data-toggle="modal" data-target="#deleteModal">Delete</button>
            {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>


    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="deleteModalLabel">Delete Post Confirmation</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <b>Are you sure to delete this post??</b>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
              <form action="{{url_for('posts.post_delete', post_id = post.id)}}" method="POST">
                  <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
          </div>
        </div>
    </div>
{% endblock content %}

app/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirmpassword.label(class="form-control-label") }}
                    {% if form.confirmpassword.errors %}
                        {{ form.confirmpassword(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirmpassword.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirmpassword(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

app/templates/reset_password.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Request Password</legend>
                <div class = "form-group">
                    {{ form.password.label(class = "form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class = "form-group">
                    {{ form.confirmpassword.label(class = "form-control-label") }}
                    {% if form.confirmpassword.errors %}
                        {{ form.confirmpassword(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirmpassword.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirmpassword(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
                <div class = "form-group">
                    {{ form.submit(class = "btn btn-outline-info") }}
                </div>
        </form>
    </div>
{% endblock content %}

app/templates/user_posts.html
{% extends "layout.html" %}

{% block content %}
    <div class="media">
        <img class="rounded-circle account-img" src=" {{ image }} ">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    {% for post in post.items %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src=" {{ url_for('static', filename='profile_pics/' + post.author.image_file)}}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime("%d/%m/%Y  %I:%M %p") }}</small>
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
    {% for page_num in post.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
      {% if page_num %}
        {% if post.page == page_num %}
          <span class="btn btn-outline-info mb-4 active">{{ page_num }}</span>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_post', username = user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}